import { StyleSheet } from 'react-native';

import {
  PLAYER_STRIP_CARD_WIDTH,
  PLAYER_STRIP_GAP,
  PLAYER_STRIP_SIDE_INSET,
} from '@/lib/game-screen/leaderboardStrip';
import { withAlpha } from '@/utils/gameScreenTheme';

import { UI } from './gameScreenUi';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: UI.black,
  },
  starfieldDim: {
    ...StyleSheet.absoluteFill,
  },
  pageWash: {
    ...StyleSheet.absoluteFill,
  },
  container: {
    paddingHorizontal: 8,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 8,
  },
  heroStickyShell: {
    zIndex: 4,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  heroCard: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 10,
    gap: 6,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  heroHeaderCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
  },
  heroEyebrow: {
    color: UI.textMuted,
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  nameBadge: {
    borderRadius: 8,
    borderWidth: 1,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  nameBadgeText: {
    color: UI.text,
    fontSize: 16,
    fontWeight: '800',
    flexShrink: 1,
    textAlign: 'center',
  },
  roundBadge: {
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  roundBadgeText: {
    color: UI.text,
    fontSize: 10,
    fontWeight: '700',
  },
  commandButton: {
    minWidth: 112,
    alignSelf: 'flex-start',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: withAlpha(UI.text, 0.16),
    backgroundColor: UI.cardMuted,
    paddingHorizontal: 9,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commandButtonText: {
    color: UI.text,
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  playerStripRow: {
    gap: PLAYER_STRIP_GAP,
    paddingHorizontal: PLAYER_STRIP_SIDE_INSET,
    alignItems: 'center',
  },
  playerPill: {
    width: PLAYER_STRIP_CARD_WIDTH,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  playerPillRail: {
    width: 7,
    height: 24,
    borderRadius: 999,
  },
  playerPillBody: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    gap: 3,
  },
  playerPillName: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '800',
    maxWidth: 90,
  },
  playerPillMetrics: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  metricChip: {
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 3,
    backgroundColor: UI.cardMuted,
    borderWidth: 1,
    borderColor: UI.line,
  },
  metricChipText: {
    color: UI.text,
    fontSize: 9,
    fontWeight: '600',
  },
  sectionCard: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 8,
    gap: 6,
  },
  directPrestigeFrame: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 5,
    gap: 3,
  },
  directPrestigeFrameMinimized: {
    paddingVertical: 8,
  },
  prestigeCounterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  prestigeStepperButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  prestigeStepperText: {
    color: UI.text,
    fontSize: 22,
    fontWeight: '800',
  },
  prestigeCenterWrap: {
    width: 96,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  prestigeValueBox: {
    width: 96,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#000000',
    borderWidth: 1.5,
    borderColor: withAlpha(UI.gold, 0.52),
    alignItems: 'center',
    justifyContent: 'center',
  },
  prestigeValueText: {
    color: UI.text,
    fontSize: 19,
    fontWeight: '800',
  },
  contractRow: {
    flexDirection: 'row',
    gap: 4,
  },
  contractButton: {
    height: 42,
    borderRadius: 8,
    borderWidth: 1.25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  contractButtonExpanded: {
    flex: 1,
  },
  contractButtonMinimized: {
    width: 56,
  },
  contractIcon: {
    fontSize: 18,
    fontWeight: '800',
  },
  contractLabel: {
    color: UI.text,
    fontSize: 10,
    fontWeight: '700',
  },
  headToHeadButton: {
    minHeight: 50,
    marginTop: 8,
    borderRadius: 10,
    borderWidth: 1.25,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  headToHeadButtonTitle: {
    color: UI.text,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  headToHeadButtonMeta: {
    color: UI.textMuted,
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  headToHeadActiveBox: {
    marginTop: 8,
    minHeight: 112,
    position: 'relative',
    borderRadius: 10,
    borderWidth: 1.25,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
    overflow: 'hidden',
  },
  headToHeadActiveBody: {
    minHeight: 112,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  headToHeadActiveTitle: {
    color: UI.text,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  headToHeadActiveSummaryWrap: {
    position: 'absolute',
    left: 0,
    bottom: 0,
  },
  headToHeadActiveMeta: {
    color: '#eef2f7',
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'left',
  },
  headToHeadOrdinalSuffix: {
    fontSize: 7,
    lineHeight: 10,
    fontWeight: '700',
    transform: [{ translateY: -3 }],
  },
  headToHeadActiveFooter: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  headToHeadActiveClearButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: withAlpha(UI.silver, 0.42),
    backgroundColor: withAlpha(UI.silver, 0.14),
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  headToHeadActiveClearText: {
    color: UI.text,
    fontSize: 9,
    fontWeight: '700',
  },
  baseModeBoxElite: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: withAlpha(UI.gold, 0.72),
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  baseModeTextElite: {
    color: UI.gold,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  sectionTitle: {
    color: UI.text,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  headerTapZone: {
    flex: 1,
    borderRadius: 8,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chevron: {
    color: UI.textMuted,
    fontSize: 14,
    fontWeight: '700',
  },
  assistHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  assistHeaderRight: {
  flexDirection: 'row',
  alignItems: 'center',
  flex: 1,
},

assistDotsScroll: {
  flexGrow: 0,
  flexShrink: 1,
},

assistHeaderActions: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
  paddingLeft: 6,
},

noneChip: {
  marginLeft: 'auto',
  minWidth: 66,
  height: 36,
  borderRadius: 8,
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: 1,
  borderColor: UI.lineStrong,
  backgroundColor: UI.cardMuted,
},
  noneChipText: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '600',
  },
  headerRestoreDotButton: {
    width: 24,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRestoreDotOnly: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  rowsStack: {
    gap: 0,
  },
  playerRowCard: {
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 7,
    overflow: 'hidden',
  },
  playerRowCardQuiet: {
    backgroundColor: UI.cardMuted,
    borderColor: UI.line,
    opacity: 0.92,
  },
  assistSingleLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  assistNameWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    minWidth: 78,
    flexShrink: 1,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  assistNameWrapQuiet: {
    backgroundColor: UI.cardMuted,
    borderColor: UI.line,
  },
  assistInlineControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
  },
  assistInlinePrestige: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  colorBullet: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  playerRowTitle: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '700',
  },
  playerRowTitleQuiet: {
    color: UI.textMuted,
  },
  choiceChip: {
    minWidth: 48,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceChipQuiet: {
    borderColor: UI.line,
    backgroundColor: UI.cardMuted,
  },
  choiceChipText: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '600',
  },
  miniStepper: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: UI.line,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: UI.cardMuted,
  },
  miniStepperText: {
    color: UI.text,
    fontSize: 15,
    fontWeight: '700',
  },
  miniValue: {
    color: UI.text,
    fontSize: 15,
    fontWeight: '700',
    minWidth: 14,
    textAlign: 'center',
  },
  objectiveRowCard: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  objectiveRowCardQuiet: {
    backgroundColor: UI.cardMuted,
    borderColor: UI.line,
    opacity: 0.92,
  },
  objectiveNameWrap: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginRight: 6,
  },
  objectiveNameWrapQuiet: {
    backgroundColor: UI.cardMuted,
    borderColor: UI.line,
  },
  objectiveName: {
    color: UI.text,
    fontSize: 12,
    fontWeight: '700',
  },
  objectiveNameQuiet: {
    color: UI.textMuted,
  },
  objectiveControlsRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  objectiveMiniButton: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: UI.line,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: UI.cardMuted,
  },
  objectiveMiniButtonText: {
    color: UI.text,
    fontSize: 15,
    fontWeight: '700',
  },
  objectiveValuePill: {
    minWidth: 40,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: UI.cardMuted,
    borderWidth: 1,
    borderColor: UI.line,
  },
  objectiveValueText: {
    color: UI.text,
    fontSize: 14,
    fontWeight: '700',
  },
  previousRoundRow: {
    borderRadius: 10,
    borderWidth: 1,
    minHeight: 36,
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  previousRoundText: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '700',
  },
  previousRoundMetric: {
    color: UI.textMuted,
    fontSize: 10,
    fontWeight: '500',
  },
  undoLastTurnButton: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  undoLastTurnButtonDisabled: {
    opacity: 0.4,
  },
  undoLastTurnText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  actionsWrap: {
    gap: 5,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 6,
  },
  actionButton: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  actionButtonCompact: {
    minHeight: 38,
    paddingVertical: 5,
  },
  actionButtonTall: {
    minHeight: 76,
    paddingVertical: 12,
  },
  secondaryAction: {
    backgroundColor: UI.cardMuted,
    borderColor: UI.lineStrong,
  },
  baseAction: {
    backgroundColor: '#0a0a0a',
    borderColor: withAlpha(UI.gold, 0.36),
  },
  baseActionActive: {
    backgroundColor: '#000000',
    borderColor: withAlpha(UI.gold, 0.68),
  },
  baseActionText: {
    color: UI.gold,
  },
  endTurnAction: {
    backgroundColor: withAlpha(UI.success, 0.08),
    borderColor: withAlpha(UI.success, 0.34),
  },
  finishAction: {
    backgroundColor: withAlpha(UI.failure, 0.08),
    borderColor: withAlpha(UI.failure, 0.32),
  },
  actionText: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  disabled: {
    opacity: 0.45,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: UI.text,
    fontSize: 18,
    fontWeight: '800',
  },
});
