import { CompareRow, MetricDescriptor, MetricGroup } from './compareTypes';
import { formatCorrelation, formatPercent, formatSigned } from './compareHelpers';

export const METRIC_GROUPS: MetricGroup[] = [
  { key: 'outcomes', label: 'Outcomes', accent: '#22c55e' },
  { key: 'prestige', label: 'Prestige', accent: '#60a5fa' },
  { key: 'assists', label: 'Assists', accent: '#22d3ee' },
  { key: 'objectives', label: 'Objectives', accent: '#8b5cf6' },
  { key: 'efficiency', label: 'Efficiency', accent: '#c084fc' },
  { key: 'positioning', label: 'Positioning', accent: '#f59e0b' },
];

function hasObjectiveData(r: CompareRow) {
  return Number(r.objectiveTrackedGames ?? 0) > 0;
}

function hasPositionData(r: CompareRow) {
  return Number(r.avgStartOrder ?? 0) > 0;
}

function hasAssistData(r: CompareRow) {
  return (
    Number(r.assists ?? 0) > 0 ||
    Number(r.assistPrestigeReceived ?? 0) > 0 ||
    Number(r.assistPrestigeSent ?? 0) > 0
  );
}

export const METRICS: MetricDescriptor[] = [
  {
    key: 'games',
    label: 'Games',
    description: 'Total saved games included for this player or group.',
    group: 'outcomes',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.games,
    format: (r) => `${r.games}`,
  },
  {
    key: 'wins',
    label: 'Wins',
    description: 'Total wins in the compared sample.',
    group: 'outcomes',
    kind: 'count',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.wins,
    format: (r) => `${r.wins}`,
  },
  {
    key: 'winRate',
    label: 'Win Rate',
    description: 'Wins divided by games played in the selected comparison sample.',
    group: 'outcomes',
    kind: 'percent',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.winRate,
    format: (r) => formatPercent(r.winRate),
  },
  {
    key: 'closeGameRate',
    label: 'Close-Game Rate',
    description: 'Share of games where the top two prestige totals finished within 3 prestige.',
    group: 'outcomes',
    kind: 'percent',
    direction: 'higher',
    getValue: (r) => r.closeGameRate,
    format: (r) => formatPercent(r.closeGameRate),
  },
  {
    key: 'dataConfidenceScore',
    label: 'Data Confidence',
    description: 'Reliability score based on sample size and data coverage for this compared row.',
    group: 'outcomes',
    kind: 'decimal',
    direction: 'higher',
    getValue: (r) => r.dataConfidenceScore,
    format: (r) => r.dataConfidenceScore.toFixed(2),
  },

  {
    key: 'prestige',
    label: 'Total Prestige',
    description: 'Combined prestige across all included games: direct, assist-in, and objective prestige.',
    group: 'prestige',
    kind: 'count',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.prestige,
    format: (r) => `${Math.round(r.prestige)}`,
  },
  {
    key: 'directPrestige',
    label: 'Direct Prestige',
    description: 'Prestige earned directly, excluding assist-in and objective prestige.',
    group: 'prestige',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.directPrestige,
    format: (r) => `${Math.round(r.directPrestige)}`,
  },
  {
    key: 'avgPrestigePerGame',
    label: 'Prestige / Game',
    description: 'Average total prestige per game in the selected sample.',
    group: 'prestige',
    kind: 'decimal',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.avgPrestigePerGame,
    format: (r) => r.avgPrestigePerGame.toFixed(1),
  },
  {
    key: 'avgPrestigeMargin',
    label: 'Avg Prestige Margin',
    description: 'Average prestige margin versus the opposing field, normalized by opponent count.',
    group: 'prestige',
    kind: 'signed',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.avgPrestigeMargin,
    format: (r) => formatSigned(r.avgPrestigeMargin),
  },

  {
    key: 'assists',
    label: 'Assists',
    description: 'Count of assists logged across included games.',
    group: 'assists',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.assists,
    format: (r) => (hasAssistData(r) ? `${r.assists}` : '—'),
  },
  {
    key: 'assistPrestigeReceived',
    label: 'Assist Prestige In',
    description: 'Prestige received from assists by other players.',
    group: 'assists',
    kind: 'decimal',
    direction: 'higher',
    getValue: (r) => r.assistPrestigeReceived,
    format: (r) => (hasAssistData(r) ? r.assistPrestigeReceived.toFixed(1) : '—'),
  },
  {
    key: 'assistPrestigeSent',
    label: 'Assist Prestige Out',
    description: 'Prestige value sent out through assists to others.',
    group: 'assists',
    kind: 'decimal',
    direction: 'neutral',
    getValue: (r) => r.assistPrestigeSent,
    format: (r) => (hasAssistData(r) ? r.assistPrestigeSent.toFixed(1) : '—'),
  },
  {
    key: 'netAssistBenefit',
    label: 'Net Assist Benefit',
    description: 'Assist prestige received minus assist prestige sent.',
    group: 'assists',
    kind: 'signed',
    direction: 'higher',
    getValue: (r) => r.netAssistBenefit,
    format: (r) => (hasAssistData(r) ? formatSigned(r.netAssistBenefit) : '—'),
  },
  {
    key: 'assistWinCorrelation',
    label: 'Assist ↔ Win Corr',
    description: 'Correlation between assists generated in a game and winning that game in the selected sample.',
    group: 'assists',
    kind: 'correlation',
    direction: 'higher',
    getValue: (r) => r.assistWinCorrelation,
    format: (r) => (hasAssistData(r) ? formatCorrelation(r.assistWinCorrelation) : '—'),
  },

  {
    key: 'objectivePrestige',
    label: 'Objective Prestige',
    description: 'Prestige earned from objectives in objective-tracked games only.',
    group: 'objectives',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.objectivePrestige,
    format: (r) => (hasObjectiveData(r) ? `${Math.round(r.objectivePrestige)}` : '—'),
  },
  {
    key: 'objectiveTrackedGames',
    label: 'Tracked Objective Games',
    description: 'Games included in the sample that were flagged as objective-tracked.',
    group: 'objectives',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.objectiveTrackedGames,
    format: (r) => (hasObjectiveData(r) ? `${r.objectiveTrackedGames}` : '—'),
  },
  {
    key: 'avgObjectivesPerTrackedGame',
    label: 'Objectives / Tracked Game',
    description: 'Average objective prestige per objective-tracked game.',
    group: 'objectives',
    kind: 'decimal',
    direction: 'higher',
    getValue: (r) => r.avgObjectivesPerTrackedGame,
    format: (r) => (hasObjectiveData(r) ? r.avgObjectivesPerTrackedGame.toFixed(2) : '—'),
  },
  {
    key: 'objectiveShareOfPrestige',
    label: 'Objective Share',
    description: 'Share of total prestige that came from objective prestige.',
    group: 'objectives',
    kind: 'percent',
    direction: 'higher',
    getValue: (r) => r.objectiveShareOfPrestige,
    format: (r) => (hasObjectiveData(r) ? formatPercent(r.objectiveShareOfPrestige) : '—'),
  },
  {
    key: 'objectiveWinRateTracked',
    label: 'Objective Win Rate',
    description: 'Win rate in objective-tracked games where the compared entity registered objective prestige.',
    group: 'objectives',
    kind: 'percent',
    direction: 'higher',
    getValue: (r) => r.objectiveWinRateTracked,
    format: (r) => (hasObjectiveData(r) ? formatPercent(r.objectiveWinRateTracked) : '—'),
  },

  {
    key: 'score',
    label: 'Score',
    description: 'Aggregate score total across included games.',
    group: 'efficiency',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.score,
    format: (r) => `${Math.round(r.score)}`,
  },
  {
    key: 'avgScorePerGame',
    label: 'Score / Game',
    description: 'Average score per game across the selected sample.',
    group: 'efficiency',
    kind: 'decimal',
    direction: 'higher',
    getValue: (r) => r.avgScorePerGame,
    format: (r) => r.avgScorePerGame.toFixed(1),
  },
  {
    key: 'efficiency',
    label: 'All Eff',
    description: 'Total output per action: (Direct Prestige + Assist Prestige) / (Contracts + Assists).',
    group: 'efficiency',
    kind: 'decimal',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.efficiency,
    format: (r) => r.efficiency.toFixed(2),
  },
  {
    key: 'assistedEfficiency',
    label: 'Assist Eff',
    description: 'Assist value per assist: Assist Prestige / Assists.',
    group: 'efficiency',
    kind: 'decimal',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.assistedEfficiency,
    format: (r) => r.assistedEfficiency.toFixed(2),
  },
  {
    key: 'directEfficiency',
    label: 'Direct Eff',
    description: 'Solo execution efficiency: Direct Prestige / Contracts.',
    group: 'efficiency',
    kind: 'decimal',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => Number(r.directEfficiency ?? 0),
    format: (r) => Number(r.directEfficiency ?? 0).toFixed(2),
  },
  {
    key: 'contracts',
    label: 'Contracts',
    description: 'Contracts completed in the compared sample.',
    group: 'efficiency',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.contracts,
    format: (r) => `${r.contracts}`,
  },
  {
    key: 'failures',
    label: 'Failures',
    description: 'Failures logged across included games.',
    group: 'efficiency',
    kind: 'count',
    direction: 'lower',
    getValue: (r) => r.failures,
    format: (r) => `${r.failures}`,
  },
  {
    key: 'contractFailureRatio',
    label: 'Contract / Failure Ratio',
    description: 'Contracts divided by failures. Higher means stronger contract conversion relative to failures.',
    group: 'efficiency',
    kind: 'decimal',
    direction: 'higher',
    getValue: (r) => r.contractFailureRatio,
    format: (r) => r.contractFailureRatio.toFixed(2),
  },
  {
    key: 'avgScoreMargin',
    label: 'Avg Score Margin',
    description: 'Average score margin versus the opposing field, normalized by opponent count.',
    group: 'efficiency',
    kind: 'signed',
    direction: 'higher',
    getValue: (r) => r.avgScoreMargin,
    format: (r) => formatSigned(r.avgScoreMargin),
  },
  {
    key: 'synergyIndex',
    label: 'Synergy Index',
    description: 'Composite indicator blending win rate, closeness, margins, assist interaction, and objective share.',
    group: 'efficiency',
    kind: 'decimal',
    direction: 'higher',
    topMetric: true,
    getValue: (r) => r.synergyIndex,
    format: (r) => r.synergyIndex.toFixed(3),
  },

  {
    key: 'avgStartOrder',
    label: 'Avg Start Order',
    description: 'Average recorded start position across included games.',
    group: 'positioning',
    kind: 'decimal',
    direction: 'lower',
    getValue: (r) => r.avgStartOrder,
    format: (r) => (hasPositionData(r) ? r.avgStartOrder.toFixed(2) : '—'),
  },
  {
    key: 'turnOrderWinCorrelation',
    label: 'Seat Adv. Spread',
    description: 'Win-rate gap between the best and worst starting seat in the selected sample. Negative means earlier seats win more often.',
    group: 'positioning',
    kind: 'correlation',
    direction: 'lower',
    getValue: (r) => r.turnOrderWinCorrelation,
    format: (r) => (hasPositionData(r) ? formatCorrelation(r.turnOrderWinCorrelation) : '—'),
  },
  {
    key: 'closeGames',
    label: 'Close Games',
    description: 'Count of included games classified as close finishes.',
    group: 'positioning',
    kind: 'count',
    direction: 'higher',
    getValue: (r) => r.closeGames,
    format: (r) => `${r.closeGames}`,
  },
];
