export const APP_ICONS = {
  addRemoves: require("../assets/icons/add_remove.png"),
  billBendo: require("../assets/icons/Bill_Bendo.png"),
  blueHub: require("../assets/icons/Blue.png"),
  charts: require("../assets/icons/Mission Card.png"),
  compare: require("../assets/icons/Green.png"),
  damage: require("../assets/icons/damage.png"),
  definitions: require("../assets/icons/definitions.png"),
  elo: require("../assets/icons/elo.png"),
  fullProfile: require("../assets/icons/Yellow 2.png"),
  hazardDieHub: require("../assets/icons/Hazard_Die.png"),
  greenHub: require("../assets/icons/Green.png"),
  history: require("../assets/icons/history.png"),
  missionCardHub: require("../assets/icons/Mission Card.png"),
  missionHub: require("../assets/icons/Mission.png"),
  miss: require("../assets/icons/miss.png"),
  moneyHub: require("../assets/icons/Money.png"),
  objectiveHub: require("../assets/icons/Objective.png"),
  orangePerson: require("../assets/icons/orange_person.png"),
  playerCard: require("../assets/icons/player_card.png"),
  prestigeHub: require("../assets/icons/Prestige.png"),
  purpleHub: require("../assets/icons/Purple.png"),
  reactor: require("../assets/icons/reactor.png"),
  shield: require("../assets/icons/shield.png"),
  ships: require("../assets/icons/ships.png"),
  statistics: require("../assets/icons/Prestige.png"),
  thruster: require("../assets/icons/thruster.png"),
  yellowHub: require("../assets/icons/Yellow.png"),
} as const;

export type AppIconKey = keyof typeof APP_ICONS;
